/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SheetgenRouteRouteImport } from './routes/sheetgen/route'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetgenIndexRouteImport } from './routes/sheetgen/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as SheetgenVampireRouteImport } from './routes/sheetgen/vampire'
import { Route as SheetgenDnd2RouteImport } from './routes/sheetgen/dnd2'
import { Route as SheetgenDndRouteImport } from './routes/sheetgen/dnd'
import { Route as SheetgenCyberpunkRouteImport } from './routes/sheetgen/cyberpunk'
import { Route as ProductsIdIndexRouteImport } from './routes/products/$id/index'

const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetgenRouteRoute = SheetgenRouteRouteImport.update({
  id: '/sheetgen',
  path: '/sheetgen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetgenIndexRoute = SheetgenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SheetgenRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const SheetgenVampireRoute = SheetgenVampireRouteImport.update({
  id: '/vampire',
  path: '/vampire',
  getParentRoute: () => SheetgenRouteRoute,
} as any)
const SheetgenDnd2Route = SheetgenDnd2RouteImport.update({
  id: '/dnd2',
  path: '/dnd2',
  getParentRoute: () => SheetgenRouteRoute,
} as any)
const SheetgenDndRoute = SheetgenDndRouteImport.update({
  id: '/dnd',
  path: '/dnd',
  getParentRoute: () => SheetgenRouteRoute,
} as any)
const SheetgenCyberpunkRoute = SheetgenCyberpunkRouteImport.update({
  id: '/cyberpunk',
  path: '/cyberpunk',
  getParentRoute: () => SheetgenRouteRoute,
} as any)
const ProductsIdIndexRoute = ProductsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => ProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/sheetgen': typeof SheetgenRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/imprint': typeof ImprintRoute
  '/sheetgen/cyberpunk': typeof SheetgenCyberpunkRoute
  '/sheetgen/dnd': typeof SheetgenDndRoute
  '/sheetgen/dnd2': typeof SheetgenDnd2Route
  '/sheetgen/vampire': typeof SheetgenVampireRoute
  '/products/': typeof ProductsIndexRoute
  '/sheetgen/': typeof SheetgenIndexRoute
  '/products/$id': typeof ProductsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/imprint': typeof ImprintRoute
  '/sheetgen/cyberpunk': typeof SheetgenCyberpunkRoute
  '/sheetgen/dnd': typeof SheetgenDndRoute
  '/sheetgen/dnd2': typeof SheetgenDnd2Route
  '/sheetgen/vampire': typeof SheetgenVampireRoute
  '/products': typeof ProductsIndexRoute
  '/sheetgen': typeof SheetgenIndexRoute
  '/products/$id': typeof ProductsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/sheetgen': typeof SheetgenRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/imprint': typeof ImprintRoute
  '/sheetgen/cyberpunk': typeof SheetgenCyberpunkRoute
  '/sheetgen/dnd': typeof SheetgenDndRoute
  '/sheetgen/dnd2': typeof SheetgenDnd2Route
  '/sheetgen/vampire': typeof SheetgenVampireRoute
  '/products/': typeof ProductsIndexRoute
  '/sheetgen/': typeof SheetgenIndexRoute
  '/products/$id/': typeof ProductsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/sheetgen'
    | '/about'
    | '/blog'
    | '/imprint'
    | '/sheetgen/cyberpunk'
    | '/sheetgen/dnd'
    | '/sheetgen/dnd2'
    | '/sheetgen/vampire'
    | '/products/'
    | '/sheetgen/'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/imprint'
    | '/sheetgen/cyberpunk'
    | '/sheetgen/dnd'
    | '/sheetgen/dnd2'
    | '/sheetgen/vampire'
    | '/products'
    | '/sheetgen'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/sheetgen'
    | '/about'
    | '/blog'
    | '/imprint'
    | '/sheetgen/cyberpunk'
    | '/sheetgen/dnd'
    | '/sheetgen/dnd2'
    | '/sheetgen/vampire'
    | '/products/'
    | '/sheetgen/'
    | '/products/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  SheetgenRouteRoute: typeof SheetgenRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ImprintRoute: typeof ImprintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheetgen': {
      id: '/sheetgen'
      path: '/sheetgen'
      fullPath: '/sheetgen'
      preLoaderRoute: typeof SheetgenRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheetgen/': {
      id: '/sheetgen/'
      path: '/'
      fullPath: '/sheetgen/'
      preLoaderRoute: typeof SheetgenIndexRouteImport
      parentRoute: typeof SheetgenRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/sheetgen/vampire': {
      id: '/sheetgen/vampire'
      path: '/vampire'
      fullPath: '/sheetgen/vampire'
      preLoaderRoute: typeof SheetgenVampireRouteImport
      parentRoute: typeof SheetgenRouteRoute
    }
    '/sheetgen/dnd2': {
      id: '/sheetgen/dnd2'
      path: '/dnd2'
      fullPath: '/sheetgen/dnd2'
      preLoaderRoute: typeof SheetgenDnd2RouteImport
      parentRoute: typeof SheetgenRouteRoute
    }
    '/sheetgen/dnd': {
      id: '/sheetgen/dnd'
      path: '/dnd'
      fullPath: '/sheetgen/dnd'
      preLoaderRoute: typeof SheetgenDndRouteImport
      parentRoute: typeof SheetgenRouteRoute
    }
    '/sheetgen/cyberpunk': {
      id: '/sheetgen/cyberpunk'
      path: '/cyberpunk'
      fullPath: '/sheetgen/cyberpunk'
      preLoaderRoute: typeof SheetgenCyberpunkRouteImport
      parentRoute: typeof SheetgenRouteRoute
    }
    '/products/$id/': {
      id: '/products/$id/'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
  }
}

interface ProductsRouteRouteChildren {
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsIdIndexRoute: typeof ProductsIdIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsIdIndexRoute: ProductsIdIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

interface SheetgenRouteRouteChildren {
  SheetgenCyberpunkRoute: typeof SheetgenCyberpunkRoute
  SheetgenDndRoute: typeof SheetgenDndRoute
  SheetgenDnd2Route: typeof SheetgenDnd2Route
  SheetgenVampireRoute: typeof SheetgenVampireRoute
  SheetgenIndexRoute: typeof SheetgenIndexRoute
}

const SheetgenRouteRouteChildren: SheetgenRouteRouteChildren = {
  SheetgenCyberpunkRoute: SheetgenCyberpunkRoute,
  SheetgenDndRoute: SheetgenDndRoute,
  SheetgenDnd2Route: SheetgenDnd2Route,
  SheetgenVampireRoute: SheetgenVampireRoute,
  SheetgenIndexRoute: SheetgenIndexRoute,
}

const SheetgenRouteRouteWithChildren = SheetgenRouteRoute._addFileChildren(
  SheetgenRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  SheetgenRouteRoute: SheetgenRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ImprintRoute: ImprintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
